
#ifndef IDT_SETUP
#define IDT_SETUP

#define PIC_INITIALIZATION 0x11
#define PIC1 0x20
#define PIC2 0xA0
#define PIC1_DATA (PIC1 + 1)
#define PIC2_DATA (PIC2 + 1)

#include <stdint-gcc.h>
#include "PS2.h"
#include "printk.h"

extern void irq0_handler();
extern void irq1_handler();
extern void irq2_handler();
extern void irq3_handler();
extern void irq4_handler();
extern void irq5_handler();
extern void irq6_handler();
extern void irq7_handler();
extern void irq8_handler();
extern void irq9_handler();
extern void irq10_handler();
extern void irq11_handler();
extern void irq12_handler();
extern void irq13_handler();
extern void irq14_handler();
extern void irq15_handler();
extern void irq16_handler();
extern void irq17_handler();
extern void irq18_handler();
extern void irq19_handler();
extern void irq20_handler();
extern void irq21_handler();
extern void irq22_handler();
extern void irq23_handler();
extern void irq24_handler();
extern void irq25_handler();
extern void irq26_handler();
extern void irq27_handler();
extern void irq28_handler();
extern void irq29_handler();
extern void irq30_handler();
extern void irq31_handler();
extern void irq32_handler();
extern void irq33_handler();
extern void irq34_handler();
extern void irq35_handler();
extern void irq36_handler();
extern void irq37_handler();
extern void irq38_handler();
extern void irq39_handler();
extern void irq40_handler();
extern void irq41_handler();
extern void irq42_handler();
extern void irq43_handler();
extern void irq44_handler();
extern void irq45_handler();
extern void irq46_handler();
extern void irq47_handler();
extern void irq48_handler();
extern void irq49_handler();
extern void irq50_handler();
extern void irq51_handler();
extern void irq52_handler();
extern void irq53_handler();
extern void irq54_handler();
extern void irq55_handler();
extern void irq56_handler();
extern void irq57_handler();
extern void irq58_handler();
extern void irq59_handler();
extern void irq60_handler();
extern void irq61_handler();
extern void irq62_handler();
extern void irq63_handler();
extern void irq64_handler();
extern void irq65_handler();
extern void irq66_handler();
extern void irq67_handler();
extern void irq68_handler();
extern void irq69_handler();
extern void irq70_handler();
extern void irq71_handler();
extern void irq72_handler();
extern void irq73_handler();
extern void irq74_handler();
extern void irq75_handler();
extern void irq76_handler();
extern void irq77_handler();
extern void irq78_handler();
extern void irq79_handler();
extern void irq80_handler();
extern void irq81_handler();
extern void irq82_handler();
extern void irq83_handler();
extern void irq84_handler();
extern void irq85_handler();
extern void irq86_handler();
extern void irq87_handler();
extern void irq88_handler();
extern void irq89_handler();
extern void irq90_handler();
extern void irq91_handler();
extern void irq92_handler();
extern void irq93_handler();
extern void irq94_handler();
extern void irq95_handler();
extern void irq96_handler();
extern void irq97_handler();
extern void irq98_handler();
extern void irq99_handler();
extern void irq100_handler();
extern void irq101_handler();
extern void irq102_handler();
extern void irq103_handler();
extern void irq104_handler();
extern void irq105_handler();
extern void irq106_handler();
extern void irq107_handler();
extern void irq108_handler();
extern void irq109_handler();
extern void irq110_handler();
extern void irq111_handler();
extern void irq112_handler();
extern void irq113_handler();
extern void irq114_handler();
extern void irq115_handler();
extern void irq116_handler();
extern void irq117_handler();
extern void irq118_handler();
extern void irq119_handler();
extern void irq120_handler();
extern void irq121_handler();
extern void irq122_handler();
extern void irq123_handler();
extern void irq124_handler();
extern void irq125_handler();
extern void irq126_handler();
extern void irq127_handler();
extern void irq128_handler();
extern void irq129_handler();
extern void irq130_handler();
extern void irq131_handler();
extern void irq132_handler();
extern void irq133_handler();
extern void irq134_handler();
extern void irq135_handler();
extern void irq136_handler();
extern void irq137_handler();
extern void irq138_handler();
extern void irq139_handler();
extern void irq140_handler();
extern void irq141_handler();
extern void irq142_handler();
extern void irq143_handler();
extern void irq144_handler();
extern void irq145_handler();
extern void irq146_handler();
extern void irq147_handler();
extern void irq148_handler();
extern void irq149_handler();
extern void irq150_handler();
extern void irq151_handler();
extern void irq152_handler();
extern void irq153_handler();
extern void irq154_handler();
extern void irq155_handler();
extern void irq156_handler();
extern void irq157_handler();
extern void irq158_handler();
extern void irq159_handler();
extern void irq160_handler();
extern void irq161_handler();
extern void irq162_handler();
extern void irq163_handler();
extern void irq164_handler();
extern void irq165_handler();
extern void irq166_handler();
extern void irq167_handler();
extern void irq168_handler();
extern void irq169_handler();
extern void irq170_handler();
extern void irq171_handler();
extern void irq172_handler();
extern void irq173_handler();
extern void irq174_handler();
extern void irq175_handler();
extern void irq176_handler();
extern void irq177_handler();
extern void irq178_handler();
extern void irq179_handler();
extern void irq180_handler();
extern void irq181_handler();
extern void irq182_handler();
extern void irq183_handler();
extern void irq184_handler();
extern void irq185_handler();
extern void irq186_handler();
extern void irq187_handler();
extern void irq188_handler();
extern void irq189_handler();
extern void irq190_handler();
extern void irq191_handler();
extern void irq192_handler();
extern void irq193_handler();
extern void irq194_handler();
extern void irq195_handler();
extern void irq196_handler();
extern void irq197_handler();
extern void irq198_handler();
extern void irq199_handler();
extern void irq200_handler();
extern void irq201_handler();
extern void irq202_handler();
extern void irq203_handler();
extern void irq204_handler();
extern void irq205_handler();
extern void irq206_handler();
extern void irq207_handler();
extern void irq208_handler();
extern void irq209_handler();
extern void irq210_handler();
extern void irq211_handler();
extern void irq212_handler();
extern void irq213_handler();
extern void irq214_handler();
extern void irq215_handler();
extern void irq216_handler();
extern void irq217_handler();
extern void irq218_handler();
extern void irq219_handler();
extern void irq220_handler();
extern void irq221_handler();
extern void irq222_handler();
extern void irq223_handler();
extern void irq224_handler();
extern void irq225_handler();
extern void irq226_handler();
extern void irq227_handler();
extern void irq228_handler();
extern void irq229_handler();
extern void irq230_handler();
extern void irq231_handler();
extern void irq232_handler();
extern void irq233_handler();
extern void irq234_handler();
extern void irq235_handler();
extern void irq236_handler();
extern void irq237_handler();
extern void irq238_handler();
extern void irq239_handler();
extern void irq240_handler();
extern void irq241_handler();
extern void irq242_handler();
extern void irq243_handler();
extern void irq244_handler();
extern void irq245_handler();
extern void irq246_handler();
extern void irq247_handler();
extern void irq248_handler();
extern void irq249_handler();
extern void irq250_handler();
extern void irq251_handler();
extern void irq252_handler();
extern void irq253_handler();
extern void irq254_handler();
extern void irq255_handler();

typedef struct IDT_entry {
   uint32_t end_target_offset:16;
   uint32_t target_selector:16;
   uint64_t IST:3;
   uint64_t IGN:5;
   uint64_t type:4;
   uint64_t buf:1;
   uint64_t DPL:2;
   uint64_t P:1;
   uint64_t mid_target_offset:16;
   uint64_t start_target_offset:32;
   uint32_t IGN_reserved;
}__attribute__((packed)) IDT_entry;

IDT_entry IDT_table[256];

void IRQ_set_all_masks();
void IRQ_set_mask(unsigned char);
void IRQ_clear_mask(unsigned char);
void IRQ_end_of_interrupt(int);

/*uint64_t asm_irq_handler_table[256];*/

/*initializes the pic to 0x20-0x2F*/
void PIC_setup();
void idt_setup();

#endif
